from __future__ import annotations


def _players():
    return [
        {"player_id": "player_a", "seat": 0, "connection_state": "connected"},
        {"player_id": "player_b", "seat": 1, "connection_state": "connected"},
    ]


FIXTURE_LIBRARY = {
    "MP-001": {
        "status": "PASS",
        "summary": "Fixture validates paired gameStarted + stateSnapshot(reason=gameStarted) bootstrap with snapshot as source of truth.",
        "traceId": "trace_mp001_fixture",
        "roomId": "room_mp001_fixture",
        "gameId": "game_mp001_fixture",
        "players": _players(),
        "commands": [
            {"requestId": "req_mp001_001", "actionId": "act_mp001_ready_a", "playerId": "player_a", "commandName": "setReady"},
            {"requestId": "req_mp001_002", "actionId": "act_mp001_ready_b", "playerId": "player_b", "commandName": "setReady"},
        ],
        "frames": [
            {"transportType": "helloAck", "messageId": "msg_mp001_001", "roomSequence": 1},
            {"transportType": "roomSnapshot", "messageId": "msg_mp001_002", "roomSequence": 2, "roomState": "waitingForReady"},
            {"transportType": "roomEvent", "messageId": "msg_mp001_003", "roomSequence": 3, "eventName": "memberReadyChanged"},
            {"transportType": "roomEvent", "messageId": "msg_mp001_004", "roomSequence": 4, "eventName": "roomStateChanged", "toState": "starting"},
            {"transportType": "gameEvent", "messageId": "msg_mp001_005", "roomSequence": 5, "engineEventName": "gameStarted", "eventId": "evt_mp001_001", "stateVersion": 1, "snapshotId": "snap_mp001_authority"},
            {"transportType": "gameEvent", "messageId": "msg_mp001_006", "roomSequence": 6, "engineEventName": "stateSnapshot", "eventId": "evt_mp001_002", "stateVersion": 1, "reason": "gameStarted", "snapshotId": "snap_mp001_authority", "stateHash": "hash_mp001_server"},
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp001_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 1,
                "event_id": "evt_mp001_001",
                "state_hash": "hash_mp001_a",
                "payload": {"currentPlayerId": "player_a", "turnId": 1},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp001_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 1,
                "event_id": "evt_mp001_001",
                "state_hash": "hash_mp001_b",
                "payload": {"currentPlayerId": "player_a", "turnId": 1},
            },
            "latest_server": {
                "snapshot_id": "snap_mp001_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 1,
                "event_id": "evt_mp001_002",
                "state_hash": "hash_mp001_server",
                "payload": {"roomState": "inGame", "currentPlayerId": "player_a", "turnId": 1},
            },
        },
    },
    "MP-002": {
        "status": "PASS",
        "summary": "Fixture validates deterministic terminal summary and replay metadata with locked roundEnded/matchEnded payload shape.",
        "traceId": "trace_mp002_fixture",
        "roomId": "room_mp002_fixture",
        "gameId": "game_mp002_fixture",
        "players": _players(),
        "commands": [
            {"requestId": "req_mp002_001", "actionId": "act_mp002_001", "playerId": "player_a", "commandName": "playCard"},
            {"requestId": "req_mp002_002", "actionId": "act_mp002_002", "playerId": "player_b", "commandName": "playCard"},
        ],
        "frames": [
            {"transportType": "gameEvent", "messageId": "msg_mp002_001", "roomSequence": 10, "engineEventName": "actionAccepted", "eventId": "evt_mp002_001", "stateVersion": 15},
            {"transportType": "gameEvent", "messageId": "msg_mp002_002", "roomSequence": 11, "engineEventName": "statePatched", "eventId": "evt_mp002_002", "stateVersion": 15},
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp002_003",
                "roomSequence": 12,
                "engineEventName": "roundEnded",
                "eventId": "evt_mp002_003",
                "stateVersion": 16,
                "winnerPlayerId": "player_a",
                "loserPlayerId": "player_b",
                "finalScores": [{"playerId": "player_a", "score": 7}, {"playerId": "player_b", "score": 0}],
                "settlementSummary": {"baseScore": 7, "multipliers": []},
                "endReason": "stop",
                "forfeitingPlayerId": None,
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp002_004",
                "roomSequence": 13,
                "engineEventName": "matchEnded",
                "eventId": "evt_mp002_004",
                "stateVersion": 16,
                "winnerPlayerId": "player_a",
                "loserPlayerId": "player_b",
                "finalScores": [{"playerId": "player_a", "score": 7}, {"playerId": "player_b", "score": 0}],
                "settlementSummary": {"baseScore": 7, "multipliers": []},
                "endReason": "stop",
                "forfeitingPlayerId": None,
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp002_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 12,
                "event_id": "evt_mp002_000",
                "state_hash": "hash_mp002_a",
                "payload": {"scoreboard": {"player_a": 0, "player_b": 0}},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp002_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 12,
                "event_id": "evt_mp002_000",
                "state_hash": "hash_mp002_b",
                "payload": {"scoreboard": {"player_a": 0, "player_b": 0}},
            },
            "latest_server": {
                "snapshot_id": "snap_mp002_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 16,
                "event_id": "evt_mp002_004",
                "state_hash": "hash_mp002_server",
                "payload": {
                    "winnerPlayerId": "player_a",
                    "loserPlayerId": "player_b",
                    "finalScores": [{"playerId": "player_a", "score": 7}, {"playerId": "player_b", "score": 0}],
                    "settlementSummary": {"baseScore": 7, "multipliers": []},
                    "endReason": "stop",
                    "forfeitingPlayerId": None,
                },
            },
        },
    },
    "MP-003": {
        "status": "PASS",
        "summary": "Fixture validates out-of-turn reject with unchanged stateVersion and no gameplay mutation.",
        "traceId": "trace_mp003_fixture",
        "roomId": "room_mp003_fixture",
        "gameId": "game_mp003_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp003_001",
                "actionId": "act_mp003_001",
                "playerId": "player_b",
                "commandName": "playCard",
                "expectedStateVersion": 11,
            }
        ],
        "frames": [
            {"transportType": "roomSnapshot", "messageId": "msg_mp003_001", "roomSequence": 1, "roomState": "inGame"},
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp003_002",
                "roomSequence": 2,
                "engineEventName": "actionRejected",
                "eventId": "evt_mp003_001",
                "stateVersion": 11,
                "actionId": "act_mp003_001",
                "rejectCode": "outOfTurn",
                "playerId": "player_b",
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp003_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 11,
                "event_id": "evt_mp003_000",
                "state_hash": "hash_mp003_a",
                "payload": {"currentPlayerId": "player_a", "turnId": 4},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp003_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 11,
                "event_id": "evt_mp003_000",
                "state_hash": "hash_mp003_b",
                "payload": {"currentPlayerId": "player_a", "turnId": 4},
            },
            "latest_server": {
                "snapshot_id": "snap_mp003_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 11,
                "event_id": "evt_mp003_001",
                "state_hash": "hash_mp003_server",
                "payload": {"currentPlayerId": "player_a", "turnId": 4},
            },
        },
    },
    "MP-004": {
        "status": "PASS",
        "summary": "Fixture validates duplicate actionId replay with reused eventId and no second mutation.",
        "traceId": "trace_mp004_fixture",
        "roomId": "room_mp004_fixture",
        "gameId": "game_mp004_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp004_001",
                "actionId": "act_dup_001",
                "playerId": "player_a",
                "commandName": "playCard",
                "expectedStateVersion": 20,
            },
            {
                "requestId": "req_mp004_002",
                "actionId": "act_dup_001",
                "playerId": "player_a",
                "commandName": "playCard",
                "expectedStateVersion": 20,
            },
        ],
        "frames": [
            {"transportType": "gameEvent", "messageId": "msg_mp004_001", "roomSequence": 1, "engineEventName": "actionAccepted", "eventId": "evt_mp004_001", "stateVersion": 21, "actionId": "act_dup_001"},
            {"transportType": "gameEvent", "messageId": "msg_mp004_002", "roomSequence": 2, "engineEventName": "statePatched", "eventId": "evt_mp004_002", "stateVersion": 21, "actionId": "act_dup_001"},
            {"transportType": "gameEvent", "messageId": "msg_mp004_003", "roomSequence": 3, "engineEventName": "actionAccepted", "eventId": "evt_mp004_001", "stateVersion": 21, "actionId": "act_dup_001"},
            {"transportType": "gameEvent", "messageId": "msg_mp004_004", "roomSequence": 4, "engineEventName": "statePatched", "eventId": "evt_mp004_002", "stateVersion": 21, "actionId": "act_dup_001"},
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp004_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 20,
                "event_id": "evt_mp004_000",
                "state_hash": "hash_mp004_a",
                "payload": {"currentPlayerId": "player_a"},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp004_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 20,
                "event_id": "evt_mp004_000",
                "state_hash": "hash_mp004_b",
                "payload": {"currentPlayerId": "player_a"},
            },
            "latest_server": {
                "snapshot_id": "snap_mp004_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 21,
                "event_id": "evt_mp004_002",
                "state_hash": "hash_mp004_server",
                "payload": {"currentPlayerId": "player_b"},
            },
        },
    },
    "MP-005": {
        "status": "PASS",
        "summary": "Fixture validates invalidChoice reject while the authoritative pending choice remains active.",
        "traceId": "trace_mp005_fixture",
        "roomId": "room_mp005_fixture",
        "gameId": "game_mp005_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp005_001",
                "actionId": "act_mp005_001",
                "playerId": "player_a",
                "commandName": "selectCapture",
                "expectedStateVersion": 13,
            }
        ],
        "frames": [
            {"transportType": "gameEvent", "messageId": "msg_mp005_001", "roomSequence": 1, "engineEventName": "choiceRequested", "eventId": "evt_mp005_001", "stateVersion": 13, "choiceId": "choice_mp005", "choiceKind": "capture"},
            {"transportType": "gameEvent", "messageId": "msg_mp005_002", "roomSequence": 2, "engineEventName": "actionRejected", "eventId": "evt_mp005_002", "stateVersion": 13, "actionId": "act_mp005_001", "rejectCode": "invalidChoice", "choiceId": "choice_mp005", "choiceKind": "capture", "rejectedCode": "capture.invalid"},
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp005_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 13,
                "event_id": "evt_mp005_001",
                "state_hash": "hash_mp005_a",
                "payload": {"pendingChoice": {"choiceId": "choice_mp005", "choiceKind": "capture"}},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp005_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 13,
                "event_id": "evt_mp005_001",
                "state_hash": "hash_mp005_b",
                "payload": {"pendingChoice": {"choiceId": "choice_mp005", "choiceKind": "capture"}},
            },
            "latest_server": {
                "snapshot_id": "snap_mp005_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 13,
                "event_id": "evt_mp005_002",
                "state_hash": "hash_mp005_server",
                "payload": {"pendingChoice": {"choiceId": "choice_mp005", "choiceKind": "capture"}},
            },
        },
    },
    "MP-006": {
        "status": "PASS",
        "summary": "Fixture validates snapshot-first reconnect ordering and post-resume hash equality.",
        "traceId": "trace_mp006_fixture",
        "roomId": "room_mp006_fixture",
        "gameId": "game_mp006_fixture",
        "players": _players(),
        "commands": [
            {"requestId": "req_mp006_001", "actionId": "act_mp006_resume", "playerId": "player_b", "commandName": "hello", "resumeMode": "resume"},
        ],
        "frames": [
            {"transportType": "roomEvent", "messageId": "msg_mp006_001", "roomSequence": 20, "eventName": "playerDisconnected", "playerId": "player_b", "graceExpiresAt": "2026-03-08T18:35:00+09:00"},
            {"transportType": "helloAck", "messageId": "msg_mp006_002", "roomSequence": 21, "resumeMode": "resume", "reconnectGraceMs": 30000},
            {"transportType": "roomSnapshot", "messageId": "msg_mp006_003", "roomSequence": 22, "roomState": "inGame"},
            {"transportType": "gameEvent", "messageId": "msg_mp006_004", "roomSequence": 23, "engineEventName": "stateSnapshot", "eventId": "evt_mp006_001", "stateVersion": 23, "reason": "resume", "stateHash": "hash_mp006_resume"},
            {"transportType": "roomEvent", "messageId": "msg_mp006_005", "roomSequence": 24, "eventName": "playerReconnected", "playerId": "player_b", "connectionId": "conn_mp006_new"},
            {"transportType": "gameEvent", "messageId": "msg_mp006_006", "roomSequence": 25, "engineEventName": "turnChanged", "eventId": "evt_mp006_002", "stateVersion": 24},
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp006_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 22,
                "event_id": "evt_mp006_000",
                "state_hash": "hash_mp006_a",
                "payload": {"connectionState": "connected"},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp006_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 22,
                "event_id": "evt_mp006_000",
                "state_hash": "hash_mp006_resume",
                "payload": {"connectionState": "resyncing"},
            },
            "latest_server": {
                "snapshot_id": "snap_mp006_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 23,
                "event_id": "evt_mp006_001",
                "state_hash": "hash_mp006_resume",
                "payload": {"connectionState": "connected"},
            },
        },
    },
    "MP-007": {
        "status": "PASS",
        "summary": "Fixture validates reconnect grace expiry routed through disconnectTimeout forfeit and terminal match summary fields.",
        "traceId": "trace_mp007_fixture",
        "roomId": "room_mp007_fixture",
        "gameId": "game_mp007_fixture",
        "players": _players(),
        "commands": [
            {"requestId": "req_mp007_001", "actionId": "act_mp007_resume", "playerId": "player_b", "commandName": "hello", "resumeMode": "resume"},
        ],
        "frames": [
            {"transportType": "roomEvent", "messageId": "msg_mp007_001", "roomSequence": 30, "eventName": "playerDisconnected", "playerId": "player_b", "graceExpiresAt": "2026-03-08T18:40:00+09:00"},
            {"transportType": "error", "messageId": "msg_mp007_002", "roomSequence": 31, "errorCode": "resumeExpired"},
            {"transportType": "roomEvent", "messageId": "msg_mp007_003", "roomSequence": 32, "eventName": "playerForfeited", "playerId": "player_b", "reason": "disconnectTimeout"},
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp007_004",
                "roomSequence": 33,
                "engineEventName": "matchEnded",
                "eventId": "evt_mp007_001",
                "stateVersion": 31,
                "winnerPlayerId": "player_a",
                "loserPlayerId": "player_b",
                "finalScores": [{"playerId": "player_a", "score": 0}, {"playerId": "player_b", "score": 0}],
                "settlementSummary": None,
                "endReason": "disconnectTimeout",
                "forfeitingPlayerId": "player_b",
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp007_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 30,
                "event_id": "evt_mp007_000",
                "state_hash": "hash_mp007_a",
                "payload": {"roomState": "inGame"},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp007_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 30,
                "event_id": "evt_mp007_000",
                "state_hash": "hash_mp007_b",
                "payload": {"roomState": "inGame"},
            },
            "latest_server": {
                "snapshot_id": "snap_mp007_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 31,
                "event_id": "evt_mp007_001",
                "state_hash": "hash_mp007_server",
                "payload": {
                    "winnerPlayerId": "player_a",
                    "loserPlayerId": "player_b",
                    "finalScores": [{"playerId": "player_a", "score": 0}, {"playerId": "player_b", "score": 0}],
                    "settlementSummary": None,
                    "endReason": "disconnectTimeout",
                    "forfeitingPlayerId": "player_b",
                },
            },
        },
    },
    "MP-008": {
        "status": "PASS",
        "summary": "Fixture validates stale expectedStateVersion reject followed by authoritative stateSnapshot(reason=resync) with locked mismatch artifacts.",
        "traceId": "trace_mp008_fixture",
        "roomId": "room_mp008_fixture",
        "gameId": "game_mp008_fixture",
        "players": _players(),
        "injectionPlan": {
            "executionReadiness": "fixture-executable",
            "injectedMismatchMode": "staleExpectedStateVersion",
            "clientStateVersion": 14,
            "expectedStateVersion": 14,
            "authoritativeStateVersion": 15,
            "authoritativeEventId": "evt_mp008_001",
            "recoverySnapshotReason": "resync",
            "recoverySnapshotId": "snap_mp008_authority",
        },
        "commands": [
            {"requestId": "req_mp008_001", "actionId": "act_mp008_play", "playerId": "player_a", "commandName": "playCard", "expectedStateVersion": 14},
        ],
        "mismatchFrames": [
            {
                "kind": "injectedCursor",
                "injectedMismatchMode": "staleExpectedStateVersion",
                "clientStateVersion": 14,
                "expectedStateVersion": 14,
                "authoritativeStateVersion": 15,
                "authoritativeEventId": "evt_mp008_001",
                "recoverySnapshotReason": "resync",
                "recoverySnapshotId": "snap_mp008_authority",
                "status": "PASS",
            }
        ],
        "frames": [
            {"transportType": "gameEvent", "messageId": "msg_mp008_001", "roomSequence": 40, "engineEventName": "actionRejected", "eventId": "evt_mp008_001", "stateVersion": 15, "rejectCode": "staleStateVersion", "authoritativeStateVersion": 15},
            {"transportType": "gameEvent", "messageId": "msg_mp008_002", "roomSequence": 41, "engineEventName": "stateSnapshot", "eventId": "evt_mp008_002", "stateVersion": 15, "reason": "resync", "snapshotId": "snap_mp008_authority", "stateHash": "hash_mp008_resync"},
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp008_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 14,
                "event_id": "evt_mp008_000",
                "state_hash": "hash_mp008_stale",
                "payload": {"phase": "inTurn"},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp008_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 14,
                "event_id": "evt_mp008_000",
                "state_hash": "hash_mp008_peer",
                "payload": {"phase": "inTurn"},
            },
            "latest_server": {
                "snapshot_id": "snap_mp008_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 15,
                "event_id": "evt_mp008_002",
                "state_hash": "hash_mp008_resync",
                "payload": {"phase": "inTurn"},
            },
        },
    },
    "MP-013": {
        "status": "PASS",
        "summary": "Fixture validates askingShake actor-only visibility with non-actor redaction and no hidden hand metadata leak.",
        "traceId": "trace_mp013_fixture",
        "roomId": "room_mp013_fixture",
        "gameId": "game_mp013_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp013_001",
                "actionId": "act_mp013_bootstrap",
                "playerId": "player_a",
                "commandName": "bootstrapChoice",
                "choiceKind": "shake",
            }
        ],
        "frames": [
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp013_001",
                "roomSequence": 50,
                "engineEventName": "choiceRequested",
                "eventId": "evt_mp013_001",
                "stateVersion": 18,
                "choiceId": "choice_mp013",
                "choiceKind": "shake",
                "visibility": "actorOnly",
                "actorPlayerId": "player_a",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp013_002",
                "roomSequence": 51,
                "engineEventName": "stateSnapshot",
                "eventId": "evt_mp013_002",
                "stateVersion": 18,
                "reason": "choiceSync",
                "snapshotId": "snap_mp013_authority",
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp013_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 18,
                "event_id": "evt_mp013_002",
                "state_hash": "hash_mp013_actor",
                "payload": {
                    "pendingChoice": {
                        "choiceId": "choice_mp013",
                        "choiceKind": "shake",
                        "visibility": "actorOnly",
                        "cards": ["jan-ribbon", "jan-animal"],
                        "metadata": {"handCount": 2, "reason": "shakeEligible"},
                        "options": [
                            {"optionCode": "shake.accept", "labelKey": "choice.shake.accept"},
                            {"optionCode": "shake.decline", "labelKey": "choice.shake.decline"},
                        ],
                    }
                },
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp013_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 18,
                "event_id": "evt_mp013_002",
                "state_hash": "hash_mp013_peer",
                "payload": {
                    "pendingChoice": {
                        "choiceId": "choice_mp013",
                        "choiceKind": "shake",
                        "visibility": "actorOnly",
                        "cards": [],
                        "metadata": None,
                        "options": [],
                    }
                },
            },
            "latest_server": {
                "snapshot_id": "snap_mp013_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 18,
                "event_id": "evt_mp013_002",
                "state_hash": "hash_mp013_server",
                "payload": {
                    "choiceId": "choice_mp013",
                    "visibility": "actorOnly",
                    "actorPlayerId": "player_a",
                },
            },
        },
    },
    "MP-014": {
        "status": "PASS",
        "summary": "Fixture validates disconnected and stale replacement heartbeats are rejected while newest connection ownership remains intact.",
        "traceId": "trace_mp014_fixture",
        "roomId": "room_mp014_fixture",
        "gameId": "game_mp014_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp014_001",
                "actionId": "act_mp014_hb_disconnected",
                "playerId": "player_b",
                "commandName": "room_heartbeat",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_old",
            },
            {
                "requestId": "req_mp014_002",
                "actionId": "act_mp014_resume",
                "playerId": "player_b",
                "commandName": "room_hello",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_new",
            },
            {
                "requestId": "req_mp014_003",
                "actionId": "act_mp014_hb_stale",
                "playerId": "player_b",
                "commandName": "room_heartbeat",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_old",
            },
        ],
        "frames": [
            {
                "transportType": "roomEvent",
                "messageId": "msg_mp014_001",
                "roomSequence": 60,
                "eventName": "playerDisconnected",
                "playerId": "player_b",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_old",
            },
            {
                "transportType": "error",
                "messageId": "msg_mp014_002",
                "roomSequence": 61,
                "errorCode": "invalidResumeState",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_old",
            },
            {
                "transportType": "helloAck",
                "messageId": "msg_mp014_003",
                "roomSequence": 62,
                "resumeMode": "resume",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_new",
            },
            {
                "transportType": "error",
                "messageId": "msg_mp014_004",
                "roomSequence": 63,
                "errorCode": "staleConnectionId",
                "sessionId": "sess_mp014_b",
                "connectionId": "conn_mp014_old",
                "expectedConnectionId": "conn_mp014_new",
            },
            {
                "transportType": "roomSnapshot",
                "messageId": "msg_mp014_005",
                "roomSequence": 64,
                "roomState": "inGame",
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp014_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 19,
                "event_id": "evt_mp014_000",
                "state_hash": "hash_mp014_a",
                "payload": {"roomState": "inGame"},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp014_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 19,
                "event_id": "evt_mp014_000",
                "state_hash": "hash_mp014_b",
                "payload": {"sessionId": "sess_mp014_b", "connectionId": "conn_mp014_new"},
            },
            "latest_server": {
                "snapshot_id": "snap_mp014_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 19,
                "event_id": "evt_mp014_001",
                "state_hash": "hash_mp014_server",
                "payload": {
                    "sessionId": "sess_mp014_b",
                    "currentConnectionId": "conn_mp014_new",
                    "lastAckedRoomSequence": 64,
                    "heartbeatOwnerStable": True,
                },
            },
        },
    },
    "MP-015": {
        "status": "PASS",
        "summary": "Fixture validates premature ready stays local until waitingForReady and does not trigger invalidRoomState or passive disconnect churn.",
        "traceId": "trace_mp015_fixture",
        "roomId": "room_mp015_fixture",
        "gameId": None,
        "players": [
            {"player_id": "player_a", "seat": 0, "connection_state": "connected"},
            {"player_id": "player_b", "seat": 1, "connection_state": "connected"},
        ],
        "commands": [
            {
                "requestId": "req_mp015_001",
                "playerId": "player_a",
                "commandName": "setReady",
                "dispatch": "localGuard",
                "guardResult": "skipped",
                "guardReason": "waitingForPlayers",
                "memberCount": 1,
            },
            {
                "requestId": "req_mp015_002",
                "playerId": "player_b",
                "commandName": "room_join",
                "dispatch": "transport",
            },
        ],
        "frames": [
            {
                "transportType": "roomSnapshot",
                "messageId": "msg_mp015_001",
                "roomSequence": 1,
                "roomState": "waitingForPlayers",
                "memberCount": 1,
            },
            {
                "transportType": "roomEvent",
                "messageId": "msg_mp015_002",
                "roomSequence": 2,
                "eventName": "memberJoined",
                "playerId": "player_b",
            },
            {
                "transportType": "roomSnapshot",
                "messageId": "msg_mp015_003",
                "roomSequence": 3,
                "roomState": "waitingForReady",
                "memberCount": 2,
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp015_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 3,
                "event_id": "evt_mp015_000",
                "state_hash": "hash_mp015_a",
                "payload": {"roomState": "waitingForPlayers", "localReadyEnabled": False},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp015_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 3,
                "event_id": "evt_mp015_000",
                "state_hash": "hash_mp015_b",
                "payload": {"joined": True},
            },
            "latest_server": {
                "snapshot_id": "snap_mp015_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 3,
                "event_id": "evt_mp015_001",
                "state_hash": "hash_mp015_server",
                "payload": {
                    "roomState": "waitingForReady",
                    "memberCount": 2,
                    "localReady": False,
                    "playerDisconnectedObserved": False,
                    "invalidReadyRejected": False,
                },
            },
        },
    },
    "MP-016": {
        "status": "PASS",
        "summary": "Fixture validates seeded multiplayer gameplay reaches terminalSummary and roomClosed while every go-stop submission chooses go.",
        "traceId": "trace_mp016_fixture",
        "roomId": "room_mp016_fixture",
        "gameId": "game_mp016_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp016_001",
                "actionId": "act_mp016_play_001",
                "playerId": "player_a",
                "commandName": "playCard",
                "cardId": "card_mp016_opening",
                "stateVersion": 1,
            },
            {
                "requestId": "req_mp016_002",
                "actionId": "act_mp016_choice_001",
                "playerId": "player_a",
                "commandName": "submitChoice",
                "choiceKind": "goStop",
                "choiceId": "choice_mp016_go_001",
                "optionCode": "go",
                "stateVersion": 6,
            },
            {
                "requestId": "req_mp016_003",
                "actionId": "act_mp016_choice_002",
                "playerId": "player_a",
                "commandName": "submitChoice",
                "choiceKind": "goStop",
                "choiceId": "choice_mp016_go_002",
                "optionCode": "go",
                "stateVersion": 9,
            },
            {
                "requestId": "req_mp016_004",
                "playerId": "player_a",
                "commandName": "leaveRoom",
            },
            {
                "requestId": "req_mp016_005",
                "playerId": "player_b",
                "commandName": "leaveRoom",
            },
        ],
        "frames": [
            {
                "transportType": "roomEvent",
                "messageId": "msg_mp016_001",
                "roomSequence": 1,
                "eventName": "roomStateChanged",
                "toState": "starting",
            },
            {
                "transportType": "roomEvent",
                "messageId": "msg_mp016_002",
                "roomSequence": 2,
                "eventName": "roomStateChanged",
                "toState": "inGame",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_003",
                "roomSequence": 3,
                "engineEventName": "actionAccepted",
                "eventId": "evt_mp016_001",
                "stateVersion": 2,
                "commandName": "playCard",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_004",
                "roomSequence": 4,
                "engineEventName": "choiceRequested",
                "eventId": "evt_mp016_002",
                "stateVersion": 6,
                "choiceId": "choice_mp016_go_001",
                "choiceKind": "goStop",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_005",
                "roomSequence": 5,
                "engineEventName": "actionAccepted",
                "eventId": "evt_mp016_003",
                "stateVersion": 7,
                "commandName": "chooseGoStop",
                "optionCode": "go",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_006",
                "roomSequence": 6,
                "engineEventName": "choiceRequested",
                "eventId": "evt_mp016_004",
                "stateVersion": 9,
                "choiceId": "choice_mp016_go_002",
                "choiceKind": "goStop",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_007",
                "roomSequence": 7,
                "engineEventName": "actionAccepted",
                "eventId": "evt_mp016_005",
                "stateVersion": 10,
                "commandName": "chooseGoStop",
                "optionCode": "go",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_008",
                "roomSequence": 8,
                "engineEventName": "roundEnded",
                "eventId": "evt_mp016_006",
                "stateVersion": 12,
                "winnerPlayerId": "player_a",
                "loserPlayerId": "player_b",
                "endReason": "maxScore",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp016_009",
                "roomSequence": 9,
                "engineEventName": "matchEnded",
                "eventId": "evt_mp016_007",
                "stateVersion": 12,
                "winnerPlayerId": "player_a",
                "loserPlayerId": "player_b",
                "endReason": "maxScore",
                "forfeitingPlayerId": None,
            },
            {
                "transportType": "terminalSummary",
                "messageId": "msg_mp016_010",
                "roomSequence": 9,
                "endReason": "maxScore",
            },
            {
                "transportType": "roomEvent",
                "messageId": "msg_mp016_011",
                "roomSequence": 10,
                "eventName": "roomClosed",
                "reason": "allPlayersLeft",
            },
        ],
        "snapshots": {
            "player_a_initial": {
                "snapshot_id": "snap_mp016_player_a",
                "source": "initial",
                "scope": "player",
                "player_id": "player_a",
                "state_version": 1,
                "event_id": "evt_mp016_boot_001",
                "state_hash": "hash_mp016_a",
                "payload": {"currentPlayerId": "player_a", "phase": "inTurn", "seed": 7},
            },
            "player_b_initial": {
                "snapshot_id": "snap_mp016_player_b",
                "source": "initial",
                "scope": "player",
                "player_id": "player_b",
                "state_version": 1,
                "event_id": "evt_mp016_boot_001",
                "state_hash": "hash_mp016_b",
                "payload": {"currentPlayerId": "player_a", "phase": "inTurn", "seed": 7},
            },
            "latest_server": {
                "snapshot_id": "snap_mp016_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 10,
                "event_id": "evt_mp016_007",
                "state_hash": "hash_mp016_server",
                "payload": {
                    "selectedSeed": 7,
                    "goStopOptionCodes": ["go", "go"],
                    "goStopChoiceCount": 2,
                    "terminalEndReason": "maxScore",
                    "closedRoomState": "closed",
                    "roomClosedSeen": True,
                },
            },
        },
    },
    "MP-017": {
        "status": "PASS",
        "summary": "Fixture validates the short multiplayer probe updates captured zones before the turn hands off to the opponent.",
        "traceId": "trace_mp017_fixture",
        "roomId": "room_mp017_fixture",
        "gameId": "game_mp017_fixture",
        "players": _players(),
        "commands": [
            {
                "requestId": "req_mp017_001",
                "actionId": "act_mp017_play_001",
                "playerId": "player_a",
                "commandName": "playCard",
                "cardId": "card_mp017_host_opening",
                "stateVersion": 1,
            },
            {
                "requestId": "req_mp017_002",
                "actionId": "act_mp017_play_002",
                "playerId": "player_b",
                "commandName": "playCard",
                "cardId": "card_mp017_guest_opening",
                "stateVersion": 2,
            },
            {
                "requestId": "req_mp017_003",
                "actionId": "act_mp017_play_003",
                "playerId": "player_a",
                "commandName": "playCard",
                "cardId": "card_mp017_host_second",
                "stateVersion": 3,
            },
            {
                "requestId": "req_mp017_004",
                "actionId": "act_mp017_play_004",
                "playerId": "player_b",
                "commandName": "playCard",
                "cardId": "card_mp017_guest_second",
                "stateVersion": 4,
            },
        ],
        "frames": [
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp017_001",
                "roomSequence": 1,
                "engineEventName": "actionAccepted",
                "eventId": "evt_mp017_001",
                "stateVersion": 2,
                "commandName": "playCard",
                "playerId": "player_a",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp017_002",
                "roomSequence": 2,
                "engineEventName": "statePatched",
                "eventId": "evt_mp017_002",
                "stateVersion": 2,
                "playerId": "player_a",
                "capturedDelta": 2,
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp017_003",
                "roomSequence": 3,
                "engineEventName": "turnChanged",
                "eventId": "evt_mp017_003",
                "stateVersion": 2,
                "playerId": "player_b",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp017_004",
                "roomSequence": 4,
                "engineEventName": "actionAccepted",
                "eventId": "evt_mp017_004",
                "stateVersion": 3,
                "commandName": "playCard",
                "playerId": "player_b",
            },
            {
                "transportType": "gameEvent",
                "messageId": "msg_mp017_005",
                "roomSequence": 5,
                "engineEventName": "turnChanged",
                "eventId": "evt_mp017_005",
                "stateVersion": 3,
                "playerId": "player_a",
            },
        ],
        "snapshots": {
            "latest_server": {
                "snapshot_id": "snap_mp017_authority",
                "source": "terminal",
                "scope": "authority",
                "player_id": None,
                "state_version": 4,
                "event_id": "evt_mp017_005",
                "state_hash": "hash_mp017_server",
                "payload": {
                    "turnLimitPerPlayer": 2,
                    "captureProbeSuccessCount": 1,
                    "captureProbeFailures": [],
                    "probes": [
                        {
                            "actorPlayerId": "player_a",
                            "turnIndex": 1,
                            "authoritativeCaptureStateVersion": 2,
                            "turnPassedStateVersion": 2,
                            "renderedCaptureStateVersion": 2,
                            "expectedCapturedTotal": 2,
                        }
                    ],
                },
            },
        },
    },
}
