name: GoStop
options:
  bundleIdPrefix: com.antigravity
  xcodeVersion: 15.0
  deploymentTarget:
    iOS: "16.0"
packages:
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: 5.0.6
targets:
  GoStop:
    type: application
    platform: iOS
    sources: 
      - GoStop
      - GoStop/Assets.xcassets
    dependencies:
      - package: Yams
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: GoStop
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.antigravity.GoStop
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: GoStop/Info.plist
      properties:
        UILaunchScreen: {}
  GoStopTests:
    type: bundle.unit-test
    platform: iOS
    sources: [GoStopTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.antigravity.GoStopTests
    dependencies:
      - target: GoStop
  GoStopCLI:
    type: tool
    platform: macOS
    sources:
      - GoStopCLI
      - GoStop/Models
      - GoStop/Core
      - GoStop/Resources
    dependencies:
      - package: Yams
    settings:
      base:
        PRODUCT_NAME: GoStopCLI
